name: Commit messages

on:
  pull_request:

permissions:
  contents: read

jobs:
  commitlint:
    name: Validate commit messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6

