name: Python

on:
  pull_request:

jobs:
  lint-and-test:
    name: Ruff & Pytest
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: uv sync

      - name: Ruff
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: Pytest
        run: uv run pytest

